version: '3'

services:
  database:
    image: mysql:5.7.28
    restart: always
    environment:
      MYSQL_DATABASE: "YumNomsReservations"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: 'student'
      MYSQL_PASSWORD: 'student'
    expose: 
      - '3306'
    ports:
      - '3306:3306'

  reservations:
    build: ./
    command: >
      bash -c "./wait-for-it.sh database:3306 && npm run seed && npm run start"
    depends_on:
      - 'database'
    ports: 
      - '3010:3010'